import type { Upgrade, Stage, Achievement, GameState } from './types';

export const STORAGE_KEY = 'interstellar_egg_factory_save';

export const UPGRADES: Upgrade[] = [
  {
    id: 'stronger_chicken',
    name: '强壮母鸡',
    description: '提升每次点击的产蛋量',
    icon: '🐔',
    baseCost: 15,
    costMultiplier: 1.15,
    baseEffect: 1,
    effectType: 'click',
    unlockStage: 0,
  },
  {
    id: 'auto_feeder',
    name: '自动喂食器',
    description: '每秒自动产生少量鸡蛋',
    icon: '🍽️',
    baseCost: 50,
    costMultiplier: 1.12,
    baseEffect: 0.5,
    effectType: 'auto',
    unlockStage: 0,
  },
  {
    id: 'better_nests',
    name: '舒适鸡窝',
    description: '提升所有产蛋效率 10%',
    icon: '🪺',
    baseCost: 200,
    costMultiplier: 1.2,
    baseEffect: 0.1,
    effectType: 'multiplier',
    unlockStage: 0,
  },
  {
    id: 'farm_workers',
    name: '农场工人',
    description: '雇佣工人帮你收集鸡蛋',
    icon: '👨‍🌾',
    baseCost: 500,
    costMultiplier: 1.13,
    baseEffect: 2,
    effectType: 'auto',
    unlockStage: 0,
  },
  {
    id: 'golden_feed',
    name: '金色饲料',
    description: '大幅提升点击产蛋量',
    icon: '🌾',
    baseCost: 2000,
    costMultiplier: 1.18,
    baseEffect: 5,
    effectType: 'click',
    unlockStage: 1,
  },
  {
    id: 'egg_incubator',
    name: '智能孵化器',
    description: '每秒自动孵化更多鸡蛋',
    icon: '🔬',
    baseCost: 5000,
    costMultiplier: 1.14,
    baseEffect: 10,
    effectType: 'auto',
    unlockStage: 1,
  },
  {
    id: 'factory_line',
    name: '自动化生产线',
    description: '建立鸡蛋生产流水线',
    icon: '🏭',
    baseCost: 20000,
    costMultiplier: 1.15,
    baseEffect: 50,
    effectType: 'auto',
    unlockStage: 1,
  },
  {
    id: 'quantum_clucker',
    name: '量子产蛋器',
    description: '利用量子力学提升产蛋效率',
    icon: '⚛️',
    baseCost: 100000,
    costMultiplier: 1.16,
    baseEffect: 100,
    effectType: 'auto',
    unlockStage: 2,
  },
  {
    id: 'space_coop',
    name: '太空鸡舍',
    description: '在太空建立失重养鸡场',
    icon: '🚀',
    baseCost: 500000,
    costMultiplier: 1.17,
    baseEffect: 500,
    effectType: 'auto',
    unlockStage: 2,
  },
  {
    id: 'alien_tech',
    name: '外星科技',
    description: '借鉴外星文明的养鸡技术',
    icon: '👽',
    baseCost: 2000000,
    costMultiplier: 1.18,
    baseEffect: 2000,
    effectType: 'auto',
    unlockStage: 3,
  },
  {
    id: 'dimension_eggs',
    name: '维度产蛋',
    description: '从高维空间提取无限鸡蛋',
    icon: '🌀',
    baseCost: 10000000,
    costMultiplier: 1.19,
    baseEffect: 10000,
    effectType: 'auto',
    unlockStage: 3,
  },
  {
    id: 'cosmic_hen',
    name: '宇宙母鸡',
    description: '传说中的宇宙级别母鸡',
    icon: '✨',
    baseCost: 100000000,
    costMultiplier: 1.2,
    baseEffect: 100000,
    effectType: 'auto',
    unlockStage: 4,
  },
];

export const STAGES: Stage[] = [
  {
    id: 0,
    name: '家庭农场',
    description: '从一只母鸡开始你的创业之路',
    requiredEggs: 0,
    bgGradient: 'from-green-400 via-emerald-300 to-sky-300',
    chickenEmoji: '🐔',
    unlockMessage: '恭喜！你拥有了第一只母鸡！',
  },
  {
    id: 1,
    name: '鸡蛋工厂',
    description: '规模化生产，效率至上',
    requiredEggs: 10000,
    bgGradient: 'from-orange-400 via-amber-300 to-yellow-200',
    chickenEmoji: '🏭',
    unlockMessage: '太棒了！你的农场升级为现代化工厂！',
  },
  {
    id: 2,
    name: '太空站',
    description: '将养鸡事业拓展到外太空',
    requiredEggs: 1000000,
    bgGradient: 'from-indigo-600 via-purple-500 to-blue-400',
    chickenEmoji: '🛸',
    unlockMessage: '不可思议！你在太空建立了养鸡站！',
  },
  {
    id: 3,
    name: '星际帝国',
    description: '统治整个星系的鸡蛋贸易',
    requiredEggs: 100000000,
    bgGradient: 'from-purple-800 via-fuchsia-600 to-pink-400',
    chickenEmoji: '🌌',
    unlockMessage: '震撼！你建立了星际鸡蛋帝国！',
  },
  {
    id: 4,
    name: '宇宙霸主',
    description: '成为整个宇宙的鸡蛋之王',
    requiredEggs: 10000000000,
    bgGradient: 'from-slate-900 via-indigo-800 to-purple-600',
    chickenEmoji: '👑',
    unlockMessage: '传说级成就！你是宇宙鸡蛋霸主！',
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_egg',
    name: '第一枚鸡蛋',
    description: '点击获得第一枚鸡蛋',
    icon: '🥚',
    condition: (state) => state.totalClicks >= 1,
    reward: 10,
  },
  {
    id: 'click_100',
    name: '勤劳的农民',
    description: '累计点击 100 次',
    icon: '💪',
    condition: (state) => state.totalClicks >= 100,
    reward: 100,
  },
  {
    id: 'eggs_1k',
    name: '小有成就',
    description: '累计获得 1,000 枚鸡蛋',
    icon: '📦',
    condition: (state) => state.totalEggs >= 1000,
    reward: 500,
  },
  {
    id: 'eggs_100k',
    name: '鸡蛋大亨',
    description: '累计获得 100,000 枚鸡蛋',
    icon: '💰',
    condition: (state) => state.totalEggs >= 100000,
    reward: 10000,
  },
  {
    id: 'eggs_1m',
    name: '百万富翁',
    description: '累计获得 1,000,000 枚鸡蛋',
    icon: '🏆',
    condition: (state) => state.totalEggs >= 1000000,
    reward: 100000,
  },
  {
    id: 'auto_master',
    name: '自动化大师',
    description: '每秒产出达到 100 枚鸡蛋',
    icon: '⚡',
    condition: (state) => state.eggsPerSecond >= 100,
    reward: 5000,
  },
  {
    id: 'first_upgrade',
    name: '第一次升级',
    description: '购买第一个升级',
    icon: '⬆️',
    condition: (state) => Object.values(state.upgrades).some((v) => v > 0),
    reward: 25,
  },
  {
    id: 'upgrade_10',
    name: '升级狂人',
    description: '累计购买 10 次升级',
    icon: '📈',
    condition: (state) => Object.values(state.upgrades).reduce((a, b) => a + b, 0) >= 10,
    reward: 500,
  },
  {
    id: 'play_10min',
    name: '忠实玩家',
    description: '累计游戏时间达到 10 分钟',
    icon: '⏰',
    condition: (state) => state.playTime >= 600,
    reward: 1000,
  },
  {
    id: 'space_age',
    name: '太空时代',
    description: '进入太空站阶段',
    icon: '🌙',
    condition: (state) => state.currentStage >= 2,
    reward: 50000,
  },
  {
    id: 'galactic_ruler',
    name: '银河统治者',
    description: '进入星际帝国阶段',
    icon: '🌟',
    condition: (state) => state.currentStage >= 3,
    reward: 5000000,
  },
  {
    id: 'cosmic_king',
    name: '宇宙之王',
    description: '达到最终阶段',
    icon: '👑',
    condition: (state) => state.currentStage >= 4,
    reward: 500000000,
  },
];

export const getInitialState = (): GameState => ({
  eggs: 0,
  totalEggs: 0,
  eggsPerClick: 1,
  eggsPerSecond: 0,
  totalClicks: 0,
  currentStage: 0,
  upgrades: {},
  achievements: [],
  lastSaveTime: Date.now(),
  playTime: 0,
  multiplier: 1,
});
