import type { Item, Room, Puzzle, Position } from '../types/game';

export const ITEMS: Record<string, Item> = {
  key_bronze: {
    id: 'key_bronze',
    name: '铜钥匙',
    description: '一把锈迹斑斑的铜钥匙，不知道能打开什么门。',
    icon: 'key',
    color: '#CD7F32',
  },
  key_golden: {
    id: 'key_golden',
    name: '金钥匙',
    description: '一把闪闪发光的金钥匙，似乎很重要。',
    icon: 'key',
    color: '#FFD700',
  },
  candle: {
    id: 'candle',
    name: '蜡烛',
    description: '半截蜡烛，还能点燃。',
    icon: 'flame',
    color: '#FFF8DC',
  },
  matches: {
    id: 'matches',
    name: '火柴',
    description: '一盒火柴，还剩几根。',
    icon: 'flame-kindling',
    color: '#8B4513',
  },
  note: {
    id: 'note',
    name: '纸条',
    description: '一张泛黄的纸条，上面写着：3-7-2',
    icon: 'scroll-text',
    color: '#F5F5DC',
  },
  book_old: {
    id: 'book_old',
    name: '旧书',
    description: '一本破旧的书，里面夹着什么东西。',
    icon: 'book-open',
    color: '#8B0000',
  },
  gem_red: {
    id: 'gem_red',
    name: '红宝石',
    description: '一颗散发着诡异红光的宝石。',
    icon: 'gem',
    color: '#DC143C',
  },
  gem_blue: {
    id: 'gem_blue',
    name: '蓝宝石',
    description: '一颗闪烁着幽蓝光芒的宝石。',
    icon: 'gem',
    color: '#4169E1',
  },
};

export const PUZZLES: Record<string, Puzzle> = {
  safe_code: {
    id: 'safe_code',
    type: 'code',
    title: '密码锁',
    description: '一个三位数的密码锁，需要输入正确的密码才能打开。',
    solution: '372',
    hint: '也许纸条上有线索...',
    rewardItemId: 'key_golden',
  },
  gem_puzzle: {
    id: 'gem_puzzle',
    type: 'sequence',
    title: '宝石祭坛',
    description: '祭坛上有两个凹槽，需要按正确顺序放入宝石。',
    solution: 'red-blue',
    hint: '看看墙上的画，红与蓝的顺序...',
    unlocksDoorId: 'door_attic',
  },
};

const entrancePatrol: Position[] = [
  { x: 200, y: 150 },
  { x: 600, y: 150 },
  { x: 600, y: 350 },
  { x: 200, y: 350 },
];

const livingRoomPatrol: Position[] = [
  { x: 300, y: 200 },
  { x: 500, y: 200 },
  { x: 500, y: 400 },
  { x: 300, y: 400 },
];

export const ROOMS: Record<string, Room> = {
  entrance: {
    id: 'entrance',
    name: '入口大厅',
    description: '昏暗的入口大厅，墙上挂着老照片。',
    background: '#3d3022',
    floorColor: '#5c4a3a',
    wallColor: '#8b7355',
    playerStart: { x: 400, y: 450 },
    ghostPatrolPath: entrancePatrol,
    exits: [
      { direction: 'north', roomId: 'living_room', position: { x: 400, y: 60 }, doorId: 'door_living' },
      { direction: 'east', roomId: 'kitchen', position: { x: 740, y: 250 }, doorId: 'door_kitchen' },
    ],
    interactables: [
      {
        id: 'photo_frame',
        type: 'furniture',
        position: { x: 150, y: 100 },
        size: { width: 80, height: 100 },
        name: '老照片',
        description: '一张泛黄的全家福照片，相框背面写着数字"3"。',
      },
      {
        id: 'drawer',
        type: 'puzzle',
        position: { x: 600, y: 380 },
        size: { width: 100, height: 60 },
        name: '抽屉',
        description: '一个上锁的抽屉，上面有三位数密码锁。',
        puzzleId: 'safe_code',
        solved: false,
      },
      {
        id: 'key_bronze_pickup',
        type: 'item',
        position: { x: 250, y: 300 },
        size: { width: 40, height: 30 },
        name: '铜钥匙',
        description: '地上有一把铜钥匙。',
        givesItem: 'key_bronze',
        visible: true,
        collected: false,
      },
      {
        id: 'note_pickup',
        type: 'item',
        position: { x: 500, y: 200 },
        size: { width: 40, height: 50 },
        name: '纸条',
        description: '桌上有一张纸条。',
        givesItem: 'note',
        visible: true,
        collected: false,
      },
      {
        id: 'door_living',
        type: 'exit',
        position: { x: 370, y: 40 },
        size: { width: 60, height: 40 },
        name: '通往客厅的门',
        description: '一扇木门，通向客厅。',
        leadsTo: 'living_room',
        locked: false,
      },
      {
        id: 'door_kitchen',
        type: 'exit',
        position: { x: 720, y: 220 },
        size: { width: 40, height: 60 },
        name: '通往厨房的门',
        description: '一扇门，通向厨房。',
        leadsTo: 'kitchen',
        locked: false,
      },
      {
        id: 'cabinet_entrance',
        type: 'furniture',
        position: { x: 100, y: 350 },
        size: { width: 80, height: 100 },
        name: '柜子',
        description: '一个高大的柜子，可以躲进去。',
      },
      {
        id: 'hiding_spot_1',
        type: 'hidingSpot',
        position: { x: 100, y: 350 },
        size: { width: 80, height: 100 },
        name: '躲进柜子',
        description: '躲进柜子里躲避鬼怪。',
        hideDuration: 3000,
      },
    ],
  },
  living_room: {
    id: 'living_room',
    name: '客厅',
    description: '阴森的客厅，沙发上似乎有什么东西。',
    background: '#2d2a1f',
    floorColor: '#4a3f2d',
    wallColor: '#6b5d47',
    playerStart: { x: 400, y: 450 },
    ghostPatrolPath: livingRoomPatrol,
    exits: [
      { direction: 'south', roomId: 'entrance', position: { x: 400, y: 460 }, doorId: 'door_living' },
      { direction: 'west', roomId: 'study', position: { x: 60, y: 250 }, doorId: 'door_study' },
      { direction: 'up', roomId: 'attic', position: { x: 650, y: 100 }, doorId: 'door_attic' },
    ],
    interactables: [
      {
        id: 'sofa',
        type: 'furniture',
        position: { x: 250, y: 200 },
        size: { width: 180, height: 80 },
        name: '沙发',
        description: '一张破旧的沙发，垫子下面好像有东西。',
        givesItem: 'matches',
        visible: true,
        collected: false,
      },
      {
        id: 'painting',
        type: 'furniture',
        position: { x: 500, y: 80 },
        size: { width: 100, height: 120 },
        name: '油画',
        description: '一幅诡异的油画，画中红色的太阳在蓝色的月亮左边。',
      },
      {
        id: 'door_study',
        type: 'exit',
        position: { x: 40, y: 220 },
        size: { width: 40, height: 60 },
        name: '通往书房的门',
        description: '一扇需要铜钥匙的门。',
        leadsTo: 'study',
        requiresItem: 'key_bronze',
        locked: true,
      },
      {
        id: 'door_attic',
        type: 'exit',
        position: { x: 630, y: 70 },
        size: { width: 60, height: 40 },
        name: '通往阁楼的楼梯',
        description: '通往阁楼的楼梯，有一道魔法屏障。',
        leadsTo: 'attic',
        puzzleId: 'gem_puzzle',
        locked: true,
      },
      {
        id: 'gem_red_pickup',
        type: 'item',
        position: { x: 150, y: 350 },
        size: { width: 35, height: 35 },
        name: '红宝石',
        description: '壁炉架上有一颗红宝石在发光。',
        givesItem: 'gem_red',
        visible: true,
        collected: false,
      },
      {
        id: 'hiding_spot_2',
        type: 'hidingSpot',
        position: { x: 250, y: 200 },
        size: { width: 180, height: 80 },
        name: '躲在沙发后面',
        description: '躲在沙发后面躲避鬼怪。',
        hideDuration: 2500,
      },
    ],
  },
  kitchen: {
    id: 'kitchen',
    name: '厨房',
    description: '废弃的厨房，空气中弥漫着怪味。',
    background: '#3a3528',
    floorColor: '#524a3a',
    wallColor: '#7a6e58',
    playerStart: { x: 100, y: 250 },
    exits: [
      { direction: 'west', roomId: 'entrance', position: { x: 60, y: 250 }, doorId: 'door_kitchen' },
    ],
    interactables: [
      {
        id: 'candle_pickup',
        type: 'item',
        position: { x: 400, y: 200 },
        size: { width: 30, height: 50 },
        name: '蜡烛',
        description: '餐桌上有一根蜡烛。',
        givesItem: 'candle',
        visible: true,
        collected: false,
      },
      {
        id: 'book_old_pickup',
        type: 'item',
        position: { x: 550, y: 350 },
        size: { width: 50, height: 60 },
        name: '旧书',
        description: '架子上有一本旧书。',
        givesItem: 'book_old',
        visible: true,
        collected: false,
      },
      {
        id: 'fridge',
        type: 'furniture',
        position: { x: 600, y: 150 },
        size: { width: 70, height: 120 },
        name: '冰箱',
        description: '一台老旧的冰箱，里面空空如也。',
      },
      {
        id: 'hiding_spot_3',
        type: 'hidingSpot',
        position: { x: 400, y: 300 },
        size: { width: 120, height: 80 },
        name: '躲在桌子底下',
        description: '躲在餐桌下面躲避鬼怪。',
        hideDuration: 2000,
      },
    ],
  },
  study: {
    id: 'study',
    name: '书房',
    description: '尘封的书房，书架上摆满了旧书。',
    background: '#2a251d',
    floorColor: '#453d2e',
    wallColor: '#5d503d',
    playerStart: { x: 700, y: 250 },
    exits: [
      { direction: 'east', roomId: 'living_room', position: { x: 740, y: 250 }, doorId: 'door_study' },
    ],
    interactables: [
      {
        id: 'desk',
        type: 'furniture',
        position: { x: 300, y: 200 },
        size: { width: 150, height: 70 },
        name: '书桌',
        description: '一张老旧的书桌，抽屉里有东西。',
        givesItem: 'gem_blue',
        visible: true,
        collected: false,
      },
      {
        id: 'bookshelf',
        type: 'furniture',
        position: { x: 100, y: 80 },
        size: { width: 120, height: 200 },
        name: '书架',
        description: '满是灰尘的书架，有一本书好像可以动。',
      },
      {
        id: 'altar',
        type: 'puzzle',
        position: { x: 550, y: 300 },
        size: { width: 100, height: 80 },
        name: '宝石祭坛',
        description: '一个神秘的祭坛，上面有两个凹槽，需要按顺序放入宝石。',
        puzzleId: 'gem_puzzle',
        solved: false,
      },
      {
        id: 'hiding_spot_4',
        type: 'hidingSpot',
        position: { x: 100, y: 80 },
        size: { width: 120, height: 200 },
        name: '躲进书架暗格',
        description: '书架后面有一个暗格，可以躲进去。',
        hideDuration: 3500,
      },
    ],
  },
  attic: {
    id: 'attic',
    name: '阁楼',
    description: '昏暗的阁楼，有微弱的光芒从远处传来。',
    background: '#1f1c2c',
    floorColor: '#353042',
    wallColor: '#4a4458',
    playerStart: { x: 400, y: 420 },
    exits: [
      { direction: 'down', roomId: 'living_room', position: { x: 400, y: 460 }, doorId: 'door_attic' },
    ],
    interactables: [
      {
        id: 'exit_door',
        type: 'exit',
        position: { x: 370, y: 80 },
        size: { width: 60, height: 50 },
        name: '神秘之门',
        description: '一扇散发着微光的门，似乎通向外界...',
        leadsTo: 'victory',
        requiresItem: 'key_golden',
        locked: true,
      },
      {
        id: 'chest',
        type: 'furniture',
        position: { x: 200, y: 200 },
        size: { width: 80, height: 60 },
        name: '宝箱',
        description: '一个上了锁的宝箱。',
        requiresItem: 'key_golden',
      },
      {
        id: 'mirror',
        type: 'furniture',
        position: { x: 550, y: 150 },
        size: { width: 60, height: 100 },
        name: '镜子',
        description: '一面古老的镜子，里面好像有什么在动...',
      },
    ],
  },
};

export const INITIAL_PLAYER = {
  position: { x: 400, y: 450 },
  targetPosition: { x: 400, y: 450 },
  speed: 3,
  health: 3,
  maxHealth: 3,
  inventory: [],
  currentRoom: 'entrance',
  isHidden: false,
  facing: 'right' as const,
};

export const INITIAL_GHOST = {
  id: 'ghost_1',
  position: { x: 200, y: 150 },
  targetPosition: { x: 600, y: 150 },
  speed: 1.5,
  patrolPath: entrancePatrol,
  patrolIndex: 1,
  state: 'patrol' as const,
  detectionRadius: 100,
  alertLevel: 0,
  floatOffset: 0,
  currentRoom: 'entrance',
};

export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 500;
